name-template: 'Release v{{version}}'
tag-template: 'v{{version}}'
categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🛠 Maintenance
    labels:
      - chore
change-template: '- {{message}} ([#{{number}}]({{url}}))'
no-changes-template: 'No changes in this release.'