name: Java Build Workflow

on:
  workflow_call:
    inputs:
      maven_command:
        required: false
        type: string
        default: "clean package"
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

    secrets:
      maven_username:
        required: true
      maven_password:
        required: true   
      maven_gpg_private_key:
        required: true
      maven_gpg_passphrase:
        required: true

    outputs:
      artifact_path:
        description: 'Path to the created artifact'
        value: ${{ jobs.build.outputs.artifact_path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.upload_artifact.outputs.artifact_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.maven_username }}
          server-password: ${{ secrets.maven_password }} 
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}
          gpg-passphrase: ${{ secrets.maven_gpg_passphrase }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Sign and Deploy jar to Maven Central   
        run: |
          mvn --batch-mode verify
          mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.maven_username }}
          MAVEN_PASSWORD: ${{ secrets.maven_password }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.maven_gpg_passphrase }}