name: Create GitHub Release

on:
  workflow_call:
    inputs:
      revision:
        required: true
        type: string
      draft:
        required: false
        type: boolean
        default: false
      prerelease:
        required: false
        type: boolean
        default: false
      release_info:
        required: false
        type: string  

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0    

    - name: Pull latest changes
      run: |
        git fetch origin main
        git reset --hard origin/main
        git log -1 

    - name: Create a GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ inputs.revision }}
        release_name: Release v${{ inputs.revision }}
        body: Release v${{ inputs.revision }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
